### PR TITLE
(fix) - check protocol for https and else disable agent

### LINKED ISSUE #321: Getting FetchError when running query
Version 0.3.17 works for me so I reverted to that.

## Actual Behavior
In GraphQL Execution Result window getting error
FetchError: request to http://localhost:8081/api/graphql?profile failed, reason: write EPROTO 140519593723880:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

## Expected Behavior
Query to run without error.

## Steps to Reproduce the Problem Or Description
.graphqlrc.yml:
```
projects:
  app:
    extensions:
      endpoints:
        default:
          url: http://localhost:8081/api/graphql?profile
          headers:
            Authorization: ApiKey ***
```

Execute any query. Get error.

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.18
  - VSCode Version: 1.59.1 (Universal)
  - OS Name: macOS Big Sur
  - OS Version: 11.5.2

## Logs Of TS Server || GraphQL Language Service
NetworkHelper: operation: query
NetworkHelper: endpoint: http://localhost:8081/api/graphql?profile

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Fixes #321

This is caused by using the https agent here, we could also opt to use the regular http-agent

Screenshot 2021-12-02 at 10 57 37

### CODE REVIEW

File: src/client/network-helper.ts [hunk 1]
```diff
@@ -70,35 +70,35 @@ export class NetworkHelper {
         headers: endpoint.headers as HeadersInit,
         // this is an option that's only available in `node-fetch`, not in the standard fetch API
         // @ts-expect-error
-        agent,
+        agent: new URL(endpoint.url).protocol === 'https:' ? agent : undefined,
```
Comment (acao) [inline src/client/network-helper.ts:73]: 💯

**Review by acao — APPROVED** [review]
This should do it, thank you!
